export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";

//user
export const FETCH_USER_SUCCESS="FETCH_USER_SUCCESS";
//请求用户数据
export const FETCH_USER_REQUEST="FETCH_USER_REQUEST";
/*请求用户数据失败*/
export const FETCH_USER_ERROR="FETCH_USER_ERROR";

/*promise中间件加载*/
export const LOAD_USER="LOAD_USER";
export const LOAD_USER_PENDING="LOAD_USER_PENDING";
export const LOAD_USER_FULFILLED="LOAD_USER_FULFILLED";
export const LOAD_USER_REJECTED="LOAD_USER_REJECTED"